// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaa25OMf0KiWW0i3cL0ALy7k9v7YqiI7E',
    appId: '1:468473644377:web:13d28a9e81135191267848',
    messagingSenderId: '468473644377',
    projectId: 'ai-nutrition-assistant-e2346',
    authDomain: 'ai-nutrition-assistant-e2346.firebaseapp.com',
    storageBucket: 'ai-nutrition-assistant-e2346.firebasestorage.app',
    measurementId: 'G-SZ5M6VM4FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApkkrZLPl_j7zK3WdzFXVGSSjUtG_Itcg',
    appId: '1:468473644377:android:0da8f2de23872a8f267848',
    messagingSenderId: '468473644377',
    projectId: 'ai-nutrition-assistant-e2346',
    storageBucket: 'ai-nutrition-assistant-e2346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ5_qHjNniJm2EG_8AwCXvvptMu3mtLQ4',
    appId: '1:468473644377:ios:7686922e87701012267848',
    messagingSenderId: '468473644377',
    projectId: 'ai-nutrition-assistant-e2346',
    storageBucket: 'ai-nutrition-assistant-e2346.firebasestorage.app',
    iosBundleId: 'com.ainios.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ5_qHjNniJm2EG_8AwCXvvptMu3mtLQ4',
    appId: '1:468473644377:ios:f4d65ac6e7d52171267848',
    messagingSenderId: '468473644377',
    projectId: 'ai-nutrition-assistant-e2346',
    storageBucket: 'ai-nutrition-assistant-e2346.firebasestorage.app',
    iosBundleId: 'com.ainmacos.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaa25OMf0KiWW0i3cL0ALy7k9v7YqiI7E',
    appId: '1:468473644377:web:c92d26cd4e74b40c267848',
    messagingSenderId: '468473644377',
    projectId: 'ai-nutrition-assistant-e2346',
    authDomain: 'ai-nutrition-assistant-e2346.firebaseapp.com',
    storageBucket: 'ai-nutrition-assistant-e2346.firebasestorage.app',
    measurementId: 'G-2WNBSDWFJF',
  );
}
